#!/bin/sh
# mbtools prerm: stop the daemon on removal (an upgrade restarts it in postinst).
set -e

if [ "$1" = "remove" ] && [ -d /run/systemd/system ]; then
    systemctl disable --now mbregistry.service || true
fi

exit 0
